### ISSUE TITLE
Calclulated CRC not always of length 4

### ISSUE THREAD

**Issue by nlrb** [robertklep/node-dsmr-parser#1]
The CRC string that is a result of the calculation can be shorter than 4 characters, while the CRC always should be 4 characters (e.g. calculated: E5C, read: 0E5C). Hence an exception is thrown while the CRC is OK.

Proposed change:
`return ('0000' + crc.crc16(data).toString(16)).slice(-4).toUpperCase();`

**Comment by robertklep** [comment]
Thanks, great catch!

I released a patched version as v2.0.1
